// frontend-react/src/components/AuthGoBackBtn/AuthGoBackBtn.tsx
import { Button, Icon, Link } from 'src/ui-components';
import { AppRoutes } from 'src/utils/enums/app-routes';

export type AuthGoBackBtnProps = {};

export const AuthGoBackBtn = ({ ...props }: AuthGoBackBtnProps) => {
  return (
    <Button
      sx={{ color: 'white' }}
      variant='text'
      startIcon={<Icon name='arrow_back' />}
      size='small'
      component={Link}
      to={AppRoutes.Home}
    >
      Powrót
    </Button>
  );
};

// frontend/src/app/components/auth-go-back-btn/auth-go-back-btn.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { AppRoutes } from 'src/app/utils/enums/app-routes';
import { SharedModule } from 'src/app/utils/material/material.module';
import { ButtonComponent } from '../button/button.component';

@Component({
  selector: 'app-auth-go-back-btn',
  standalone: true,
  imports: [SharedModule, ButtonComponent],
  templateUrl: './auth-go-back-btn.component.html',
  styleUrls: ['./auth-go-back-btn.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AuthGoBackBtnComponent {
  AppRoutes = AppRoutes;
}

<button app-button [type]="'text'" [routerLink]="'/' + AppRoutes.Home">
  <mat-icon [inline]="true">arrow_back</mat-icon>
  Powrót
</button>
