// frontend-react/src/pages/Home/Home.tsx
import { useQuery } from 'react-query';
import { Header } from 'src/components/Header/Header';
import { CategoryService } from 'src/http-services/category-service';
import { Category } from 'src/models/category';
import { HomeCategoriesSearch } from 'src/pages/Home/HomeCategoriesSearch/HomeCategoriesSearch';
import { Container, Typography } from 'src/ui-components';

export async function loader() {
  return null;
}

export const Home = () => {
  const { isLoading, error, data } = useQuery<Category[]>('categories', () =>
    CategoryService.getAllCategories()
  );
  console.log(data);
  return (
    <>
      <Header />
      <Container>
        <Typography
          variant={'h4'}
          sx={{ my: 8 }}
          textAlign={'center'}
          fontWeight={'bold'}
        >
          Znajdź ludzi dzielących Twoje zainteresowania!
        </Typography>
        <HomeCategoriesSearch
          isLoading={isLoading}
          data={data}
        ></HomeCategoriesSearch>
      </Container>
    </>
  );
};

Home.displayName = 'HomePage';

// frontend/src/app/pages/home/home.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { shareReplay } from 'rxjs';
import { HeaderComponent } from 'src/app/components/header/header.component';
import { CategoryService } from 'src/app/services/category.service';
import { UiComponents } from 'src/app/utils/material/material.module';
import { HomeCategoriesSearchComponent } from './home-categories-search/home-categories-search.component';

@Component({
  selector: 'app-home',
  standalone: true,
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss'],
  imports: [CommonModule, UiComponents, HomeCategoriesSearchComponent, HeaderComponent],
})
export class HomeComponent {
  categories$ = this.categoryService.getAllCategories().pipe(shareReplay());

  constructor(private categoryService: CategoryService) {}
}

<header app-header></header>
<main class="page-container">
  <h1 class="title">Znajdź ludzi dzielących Twoje zainteresowania!</h1>
  <app-home-categories-search
    [ngClass]="{ loading: !(categories$ | async) }"
    [categories]="categories$ | async"
  ></app-home-categories-search>
</main>
